apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unguard-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: unguard-dev/applications
    repoURL: https://github.com/MfCrizz/unguard-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true