apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unguard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unguard
  sources:
    - chart: unguard
      repoURL: ghcr.io/dynatrace-oss/unguard/chart
      targetRevision: 0.8.1
      helm:
        releaseName: unguard
        valueFiles:
          - $values/unguard/values.yaml
    - repoURL: https://github.com/MfCrizz/unguard-infra.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true