apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unguard-dev-mariadb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unguard
  source:
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.4
    helm:
      releaseName: unguard-mariadb-test
      parameters:
        - name: "primary.persistence.enabled"
          value: "false"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true