apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unguard-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unguard
  sources:
    - chart: unguard
      repoURL: ghcr.io/dynatrace-oss/unguard/chart
      targetRevision: 0.8.0
      helm:
        parameters:
          - name: "mariaDB.serviceName"
            value: "unguard-mariadb-test"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true