apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unguard-dev
spec:
  project: unguard
  sources:
    - chart: mariadb
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 12.2.4
      helm:
        releaseName: unguard-mariadb
        parameters:
          - name: "service.typprimary.persistence.enabled"
            value: "false"

  destination:
    server: https://kubernetes.default.svc
    namespace: unguard

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
